# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.6-pre

EAPI=6

CRATES="
aho-corasick-0.6.4
ansi_term-0.9.0
atty-0.2.2
bindgen-0.37.4
bitflags-0.8.2
cc-1.0.6
cexpr-0.2.0
cfg-if-0.1.2
clang-sys-0.23.0
clap-2.24.2
diff-0.1.10
env_logger-0.5.10
glob-0.2.11
humantime-1.1.1
kernel32-sys-0.2.2
lazy_static-1.0.0
libc-0.2.39
libloading-0.5.0
log-0.4.1
memchr-2.0.1
nom-1.2.4
peeking_take_while-0.1.2
proc-macro2-0.3.2
quick-error-1.2.1
quote-0.5.1
regex-1.0.0
regex-syntax-0.6.0
shlex-0.1.1
strsim-0.6.0
term_size-0.3.0
termcolor-0.3.4
thread-id-3.1.0
thread_local-0.3.3
ucd-util-0.1.1
unicode-segmentation-1.2.0
unicode-width-0.1.4
unicode-xid-0.1.0
unreachable-0.1.1
utf8-ranges-1.0.0
vec_map-0.8.0
void-1.0.2
which-1.0.2
winapi-0.2.8
winapi-0.3.4
winapi-build-0.1.1
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
wincolor-0.1.6"

CARGO_FEATURES="default testing_only_libclang_3_8 testing_only_libclang_3_9 testing_only_libclang_5 testing_only_libclang_4 logging static testing_only_docs testing_only_extra_assertions"

inherit cargo

DESCRIPTION="Automatically generates Rust FFI bindings to C and C++ libraries."
HOMEPAGE="https://rust-lang-nursery.github.io/rust-bindgen/"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="BSD-3-Clause" # Update to proper Gentoo format
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=" && (>=sys-devel/clang-3.9 >=sys-devel/llvm-3.9)"
RDEPEND=""

